### ISSUE TITLE
Stuff to do to get online 

### ISSUE THREAD

**Issue by rdale1** [amoghpj/modeling-and-beyond#4]
* make github basic tutorial / find a suitable link
* make "intake" form
    - for initial promotion thru my interview series
    - self- identified "expert" 
* write a landing page 
- [x] descr/objectives for community (debatable)
- [x] request people complete intake form
- [x] instructions/github tutorial on how to use
- [x] request people take a look at community brainstorming tab

**Comment by amoghpj** [comment]
We are going to separate personal data collection from community discussions. @rdale1  will spin up a database entry interface where people can submit sensitive info like email IDs, and other public info like expertise. We can periodically rebuild a markdown page with the current info. Instructions and the link to this database should be posted on the README, along with clear details on what we intend to do with the data.

**Comment by rdale1** [comment]
I'm thinking we can make a little screencap/zoom video tutorial for the github and discord, just to briefly show people the functionality. I can post it as a blog, and have the videos on youtube for embedding in whatever else. 

- [ ] github vid
- [ ] discord vid
- [ ] database vid (what the info would be used for)
- [ ] (optional) collab database vid (so its not weird that I'm asking)

**Comment by amoghpj** [comment]
Will the github video be specific to this repository, or a more general display of github functionality?
Also, do we need a discord video?

**Comment by rdale1** [comment]
**After** we get some people: 
- [ ] poll if online database would be useful, for a) collaborators b) mentors/other modelers c) tools etc
- [ ] how do they see themselves using this resource ^^ 
- [ ] poll what features would they want

**Comment by rdale1** [comment]
- [ ] put thread posts on a google sheet -> database inclusion @rdale1 
- [ ] integrate discord and google calender for journal club days/times @rdale1 
- [ ]  google sheet + brain dump
